version: '2.4'

# you should not use this file directly, but rather via the targets in ../Makefile

# this service runs a jupyter notebook server with all of pymor's
# requirements installed and the src directory added to PYTHONPATH

# you should have a preset PYMOR_JUPYTER_TOKEN environment variable,
# then start with ```make docker_jupyter```
# and connect to the server at http://localhost:8888/?token=${PYMOR_JUPYTER_TOKEN}

# 3rd party libraries that need editing can be put in .binder/local_packages/
# These are "installed" at build time of the image and will be available
# via mount at container runtime

services:
  jupyter:
    image: presentation/22-mathmod
    build:
        context: ../
        dockerfile: .binder/Dockerfile
        args:
            NB_USER: "${NB_USER}"
            NB_UID: 1000
    ports:
        - 8888:8888
    volumes:
        - ./..:/presentation
    environment:
      - JUPYTER_TOKEN=mathmod
    restart: "no"
    # xsrf check disabled for docs viewing with chrome. Somewhat related issue: https://github.com/jupyterlab/jupyterlab/issues/6106
    # and see also https://bugs.chromium.org/p/chromium/issues/detail?id=455987
    command: >
        bash -c "jupyter notebook --ip 0.0.0.0  --notebook-dir=/presentation --NotebookApp.disable_check_xsrf=True /presentation/pymor.md"
